import { Inter } from "next/font/google";
import "./globals.css";
import NavBar from "@/components/Shared/Navbar";
import Foote from "@/components/Home/Fotter/Foote";


const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Doc House Resource",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {children}
        <Foote/>
        </body>
    </html>
  );
}
